name: Docker Image CI

on:
  push:
    branches: [ "master" ]
    paths-ignore:
      - 'Nefarius.Utilities.ExceptionEnricher/**'
      - 'agent/**'
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag wdscp:$(date +%s)
