name: Docker Image CI

on:
  push:
    branches: [ "master" ]
    paths-ignore:
      - 'lib/**'
      - 'agent/**'
      - 'tests/**'
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
        submodules: true
    
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag wdscp:$(date +%s)
